### ISSUE TITLE
Migration bugs

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/ev2#123]
https://ev2-staging-pr-122.herokuapp.com/

- [x] Company name not editable -> use default value, Jono & Becca to provide list of important project ids and corresponding company (vehicle) names
- [x] fix offers sent data migration query 
  - We decided to stick to default offer.sent = false, unless offer has been accepted or rejected.

**Comment by jonscottfilm** [comment]
1. Offers sometimes appearing as draft (solid light grey tile) regardless of actual status

![screenshot_20180118-132347](https://user-images.githubusercontent.com/28431542/35101526-cd7d4672-fc57-11e7-9e2b-26ec8e2e0534.jpg)

![screenshot_20180118-131419](https://user-images.githubusercontent.com/28431542/35101514-c4613d78-fc57-11e7-988b-2d2dd782d6d6.jpg)

**Comment by JMurphyWeb** [comment]
@jonscottfilm I think all but 3 are done on this list (including 2 in the description)

**Comment by jonscottfilm** [comment]
Presume 'all but # 3.'

**Comment by jonscottfilm** [comment]
Closing. Moving any outstanding to new issue.
