### ISSUE TITLE
Duplicate offers

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/ev2#147]
PM should be able to duplicate offers.

Still to do:
- [x] add form validation 
- [x] fix up the ui and 
- [x] make sure user gets attached to offer if they exist 
- [x] test
- [x] duplicating an unregistered user breaks app due to show template user.firstname
- [x] "updated offer" email being sent to the wrong user?

**Comment by jonscottfilm** [comment]
not sure where best to post this.

need to change EDIT/SEND buttons to CANCEL/MAKE COPY at **bottom** of page:

![image](https://user-images.githubusercontent.com/28431542/35352664-8d666e1c-013c-11e8-9a99-7079af357295.png)

**Comment by jonscottfilm** [comment]
When hitting CANCEL button, get this screen:

(right nav, but error message is not required)

![image](https://user-images.githubusercontent.com/28431542/35354001-c58b50ba-0140-11e8-96c2-8608e4a6310e.png)

**Comment by jonscottfilm** [comment]
We think the Contract override shouldn't be carried in the 'Make copy'.

Contract override is a unique setting for that individual offer. 

We should resort to system contract selection for a Copy.

**Comment by jonscottfilm** [comment]
https://github.com/karmaradio/ev2/issues/147#issuecomment-360255058 is still happening, FYI

**Comment by jonscottfilm** [comment]
Great work! A valuable feature.
